export const USER_REVIEWS_REQUEST = 'USER_REVIEWS_REQUEST';
export const USER_REVIEWS_SUCCESS = 'USER_REVIEWS_SUCCESS';
export const USER_REVIEWS_FAIL = 'USER_REVIEWS_FAIL';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';

export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAIL = 'UPDATE_REVIEW_FAIL';
