export const FORUM_POST_LIST_REQUEST = 'FORUM_POST_LIST_REQUEST';
export const FORUM_POST_LIST_SUCCESS = 'FORUM_POST_LIST_SUCCESS';
export const FORUM_POST_LIST_FAIL = 'FORUM_POST_LIST_FAIL';

export const FORUM_POST_DETAILS_REQUEST = 'FORUM_POST_DETAILS_REQUEST';
export const FORUM_POST_DETAILS_SUCCESS = 'FORUM_POST_DETAILS_SUCCESS';
export const FORUM_POST_DETAILS_FAIL = 'FORUM_POST_DETAILS_FAIL';

export const FORUM_POST_CREATE_REQUEST = 'FORUM_POST_CREATE_REQUEST';
export const FORUM_POST_CREATE_SUCCESS = 'FORUM_POST_CREATE_SUCCESS';
export const FORUM_POST_CREATE_FAIL = 'FORUM_POST_CREATE_FAIL';
export const FORUM_POST_CREATE_RESET = 'FORUM_POST_CREATE_RESET';

export const FORUM_POST_LIKE_SUCCESS = 'FORUM_POST_LIKE_SUCCESS';
export const FORUM_POST_COMMENT_SUCCESS = 'FORUM_POST_COMMENT_SUCCESS';
