export const RECIPE_LIST_REQUEST = 'RECIPE_LIST_REQUEST';
export const RECIPE_LIST_SUCCESS = 'RECIPE_LIST_SUCCESS';
export const RECIPE_LIST_FAIL = 'RECIPE_LIST_FAIL';

export const RECIPE_DETAILS_REQUEST = 'RECIPE_DETAILS_REQUEST';
export const RECIPE_DETAILS_SUCCESS = 'RECIPE_DETAILS_SUCCESS';
export const RECIPE_DETAILS_FAIL = 'RECIPE_DETAILS_FAIL';

export const RECIPE_RATE_SUCCESS = 'RECIPE_RATE_SUCCESS';
export const RECIPE_COMMENT_SUCCESS = 'RECIPE_COMMENT_SUCCESS';
export const RECIPE_LIKE_SUCCESS = 'RECIPE_LIKE_SUCCESS';
export const RECIPE_SHARE_SUCCESS = 'RECIPE_SHARE_SUCCESS';
export const RECIPE_COMMENT_LIKE_SUCCESS = 'RECIPE_COMMENT_LIKE_SUCCESS';
export const RECIPE_COMMENT_REPLY_SUCCESS = 'RECIPE_COMMENT_REPLY_SUCCESS';
