export const REFERRAL_REQUEST = 'REFERRAL_REQUEST';
export const REFERRAL_SUCCESS = 'REFERRAL_SUCCESS';
export const REFERRAL_FAIL = 'REFERRAL_FAIL';

export const REFERRAL_CODE_REQUEST = 'REFERRAL_CODE_REQUEST';
export const REFERRAL_CODE_SUCCESS = 'REFERRAL_CODE_SUCCESS';
export const REFERRAL_CODE_FAIL = 'REFERRAL_CODE_FAIL';

