export const REFERRAL_REQUEST = 'REFERRAL_REQUEST';
export const REFERRAL_SUCCESS = 'REFERRAL_SUCCESS';
export const REFERRAL_FAIL = 'REFERRAL_FAIL';

export const REFERRAL_CODE_REQUEST = 'REFERRAL_CODE_REQUEST';
export const REFERRAL_CODE_SUCCESS = 'REFERRAL_CODE_SUCCESS';
export const REFERRAL_CODE_FAIL = 'REFERRAL_CODE_FAIL';

export const SUBSCRIPTION_LIST_REQUEST = 'SUBSCRIPTION_LIST_REQUEST';
export const SUBSCRIPTION_LIST_SUCCESS = 'SUBSCRIPTION_LIST_SUCCESS';
export const SUBSCRIPTION_LIST_FAIL = 'SUBSCRIPTION_LIST_FAIL';

export const SUBSCRIPTION_CREATE_REQUEST = 'SUBSCRIPTION_CREATE_REQUEST';
export const SUBSCRIPTION_CREATE_SUCCESS = 'SUBSCRIPTION_CREATE_SUCCESS';
export const SUBSCRIPTION_CREATE_FAIL = 'SUBSCRIPTION_CREATE_FAIL';
export const SUBSCRIPTION_CREATE_RESET = 'SUBSCRIPTION_CREATE_RESET';

export const SUBSCRIPTION_CANCEL_REQUEST = 'SUBSCRIPTION_CANCEL_REQUEST';
export const SUBSCRIPTION_CANCEL_SUCCESS = 'SUBSCRIPTION_CANCEL_SUCCESS';
export const SUBSCRIPTION_CANCEL_FAIL = 'SUBSCRIPTION_CANCEL_FAIL';
