export const REWARDS_REQUEST = 'REWARDS_REQUEST';
export const REWARDS_SUCCESS = 'REWARDS_SUCCESS';
export const REWARDS_FAIL = 'REWARDS_FAIL';

export const REWARD_TRANSACTIONS_REQUEST = 'REWARD_TRANSACTIONS_REQUEST';
export const REWARD_TRANSACTIONS_SUCCESS = 'REWARD_TRANSACTIONS_SUCCESS';
export const REWARD_TRANSACTIONS_FAIL = 'REWARD_TRANSACTIONS_FAIL';

export const REDEEM_REWARD_REQUEST = 'REDEEM_REWARD_REQUEST';
export const REDEEM_REWARD_SUCCESS = 'REDEEM_REWARD_SUCCESS';
export const REDEEM_REWARD_FAIL = 'REDEEM_REWARD_FAIL';
export const REDEEM_REWARD_RESET = 'REDEEM_REWARD_RESET';

export const CAMPAIGNS_REQUEST = 'CAMPAIGNS_REQUEST';
export const CAMPAIGNS_SUCCESS = 'CAMPAIGNS_SUCCESS';
export const CAMPAIGNS_FAIL = 'CAMPAIGNS_FAIL';

export const PUBLIC_SETTINGS_REQUEST = 'PUBLIC_SETTINGS_REQUEST';
export const PUBLIC_SETTINGS_SUCCESS = 'PUBLIC_SETTINGS_SUCCESS';
export const PUBLIC_SETTINGS_FAIL = 'PUBLIC_SETTINGS_FAIL';
