export const WISHLIST_ADD_ITEM = 'WISHLIST_ADD_ITEM';
export const WISHLIST_REMOVE_ITEM = 'WISHLIST_REMOVE_ITEM';
export const WISHLIST_FETCH_REQUEST = 'WISHLIST_FETCH_REQUEST';
export const WISHLIST_FETCH_SUCCESS = 'WISHLIST_FETCH_SUCCESS';
export const WISHLIST_FETCH_FAIL = 'WISHLIST_FETCH_FAIL';
