// Admin Messages Constants
export const ADMIN_MESSAGES_CONVERSATIONS_REQUEST = 'ADMIN_MESSAGES_CONVERSATIONS_REQUEST';
export const ADMIN_MESSAGES_CONVERSATIONS_SUCCESS = 'ADMIN_MESSAGES_CONVERSATIONS_SUCCESS';
export const ADMIN_MESSAGES_CONVERSATIONS_FAIL = 'ADMIN_MESSAGES_CONVERSATIONS_FAIL';

export const ADMIN_MESSAGES_CONVERSATION_REQUEST = 'ADMIN_MESSAGES_CONVERSATION_REQUEST';
export const ADMIN_MESSAGES_CONVERSATION_SUCCESS = 'ADMIN_MESSAGES_CONVERSATION_SUCCESS';
export const ADMIN_MESSAGES_CONVERSATION_FAIL = 'ADMIN_MESSAGES_CONVERSATION_FAIL';

export const ADMIN_MESSAGES_SEND_REQUEST = 'ADMIN_MESSAGES_SEND_REQUEST';
export const ADMIN_MESSAGES_SEND_SUCCESS = 'ADMIN_MESSAGES_SEND_SUCCESS';
export const ADMIN_MESSAGES_SEND_FAIL = 'ADMIN_MESSAGES_SEND_FAIL';

export const ADMIN_MESSAGES_RESOLVE_REQUEST = 'ADMIN_MESSAGES_RESOLVE_REQUEST';
export const ADMIN_MESSAGES_RESOLVE_SUCCESS = 'ADMIN_MESSAGES_RESOLVE_SUCCESS';
export const ADMIN_MESSAGES_RESOLVE_FAIL = 'ADMIN_MESSAGES_RESOLVE_FAIL';

export const ADMIN_MESSAGES_STATS_REQUEST = 'ADMIN_MESSAGES_STATS_REQUEST';
export const ADMIN_MESSAGES_STATS_SUCCESS = 'ADMIN_MESSAGES_STATS_SUCCESS';
export const ADMIN_MESSAGES_STATS_FAIL = 'ADMIN_MESSAGES_STATS_FAIL';