export const ADMIN_SETTINGS_REQUEST = 'ADMIN_SETTINGS_REQUEST';
export const ADMIN_SETTINGS_SUCCESS = 'ADMIN_SETTINGS_SUCCESS';
export const ADMIN_SETTINGS_FAIL = 'ADMIN_SETTINGS_FAIL';

export const ADMIN_SETTINGS_UPDATE_REQUEST = 'ADMIN_SETTINGS_UPDATE_REQUEST';
export const ADMIN_SETTINGS_UPDATE_SUCCESS = 'ADMIN_SETTINGS_UPDATE_SUCCESS';
export const ADMIN_SETTINGS_UPDATE_FAIL = 'ADMIN_SETTINGS_UPDATE_FAIL';

export const ADMIN_SETTINGS_RESET_REQUEST = 'ADMIN_SETTINGS_RESET_REQUEST';
export const ADMIN_SETTINGS_RESET_SUCCESS = 'ADMIN_SETTINGS_RESET_SUCCESS';
export const ADMIN_SETTINGS_RESET_FAIL = 'ADMIN_SETTINGS_RESET_FAIL';

export const ADMIN_NOTIFICATION_SEND_REQUEST = 'ADMIN_NOTIFICATION_SEND_REQUEST';
export const ADMIN_NOTIFICATION_SEND_SUCCESS = 'ADMIN_NOTIFICATION_SEND_SUCCESS';
export const ADMIN_NOTIFICATION_SEND_FAIL = 'ADMIN_NOTIFICATION_SEND_FAIL';

export const ADMIN_RECIPES_LIST_REQUEST = 'ADMIN_RECIPES_LIST_REQUEST';
export const ADMIN_RECIPES_LIST_SUCCESS = 'ADMIN_RECIPES_LIST_SUCCESS';
export const ADMIN_RECIPES_LIST_FAIL = 'ADMIN_RECIPES_LIST_FAIL';

export const PUBLIC_SETTINGS_REQUEST = 'PUBLIC_SETTINGS_REQUEST';
export const PUBLIC_SETTINGS_SUCCESS = 'PUBLIC_SETTINGS_SUCCESS';
export const PUBLIC_SETTINGS_FAIL = 'PUBLIC_SETTINGS_FAIL';