export const ADMIN_PAYMENT_STATS_REQUEST = 'ADMIN_PAYMENT_STATS_REQUEST';
export const ADMIN_PAYMENT_STATS_SUCCESS = 'ADMIN_PAYMENT_STATS_SUCCESS';
export const ADMIN_PAYMENT_STATS_FAIL = 'ADMIN_PAYMENT_STATS_FAIL';

export const ADMIN_TRANSACTIONS_REQUEST = 'ADMIN_TRANSACTIONS_REQUEST';
export const ADMIN_TRANSACTIONS_SUCCESS = 'ADMIN_TRANSACTIONS_SUCCESS';
export const ADMIN_TRANSACTIONS_FAIL = 'ADMIN_TRANSACTIONS_FAIL';

export const ADMIN_PAYOUTS_LIST_REQUEST = 'ADMIN_PAYOUTS_LIST_REQUEST';
export const ADMIN_PAYOUTS_LIST_SUCCESS = 'ADMIN_PAYOUTS_LIST_SUCCESS';
export const ADMIN_PAYOUTS_LIST_FAIL = 'ADMIN_PAYOUTS_LIST_FAIL';

export const ADMIN_REFUND_REQUEST = 'ADMIN_REFUND_REQUEST';
export const ADMIN_REFUND_SUCCESS = 'ADMIN_REFUND_SUCCESS';
export const ADMIN_REFUND_FAIL = 'ADMIN_REFUND_FAIL';

export const ADMIN_PAYOUT_RELEASE_REQUEST = 'ADMIN_PAYOUT_RELEASE_REQUEST';
export const ADMIN_PAYOUT_RELEASE_SUCCESS = 'ADMIN_PAYOUT_RELEASE_SUCCESS';
export const ADMIN_PAYOUT_RELEASE_FAIL = 'ADMIN_PAYOUT_RELEASE_FAIL';

export const ADMIN_PAYMENT_FLAG_REQUEST = 'ADMIN_PAYMENT_FLAG_REQUEST';
export const ADMIN_PAYMENT_FLAG_SUCCESS = 'ADMIN_PAYMENT_FLAG_SUCCESS';
export const ADMIN_PAYMENT_FLAG_FAIL = 'ADMIN_PAYMENT_FLAG_FAIL';

export const ADMIN_PAYMENT_EXPORT_REQUEST = 'ADMIN_PAYMENT_EXPORT_REQUEST';
export const ADMIN_PAYMENT_EXPORT_SUCCESS = 'ADMIN_PAYMENT_EXPORT_SUCCESS';
export const ADMIN_PAYMENT_EXPORT_FAIL = 'ADMIN_PAYMENT_EXPORT_FAIL';

export const ADMIN_COD_SETTLEMENTS_REQUEST = 'ADMIN_COD_SETTLEMENTS_REQUEST';
export const ADMIN_COD_SETTLEMENTS_SUCCESS = 'ADMIN_COD_SETTLEMENTS_SUCCESS';
export const ADMIN_COD_SETTLEMENTS_FAIL = 'ADMIN_COD_SETTLEMENTS_FAIL';

export const ADMIN_SETTLE_COD_REQUEST = 'ADMIN_SETTLE_COD_REQUEST';
export const ADMIN_SETTLE_COD_SUCCESS = 'ADMIN_SETTLE_COD_SUCCESS';
export const ADMIN_SETTLE_COD_FAIL = 'ADMIN_SETTLE_COD_FAIL';