export const KYC_APPLICATIONS_REQUEST = 'KYC_APPLICATIONS_REQUEST';
export const KYC_APPLICATIONS_SUCCESS = 'KYC_APPLICATIONS_SUCCESS';
export const KYC_APPLICATIONS_FAIL = 'KYC_APPLICATIONS_FAIL';

export const APPROVE_KYC_REQUEST = 'APPROVE_KYC_REQUEST';
export const APPROVE_KYC_SUCCESS = 'APPROVE_KYC_SUCCESS';
export const APPROVE_KYC_FAIL = 'APPROVE_KYC_FAIL';

export const REJECT_KYC_REQUEST = 'REJECT_KYC_REQUEST';
export const REJECT_KYC_SUCCESS = 'REJECT_KYC_SUCCESS';
export const REJECT_KYC_FAIL = 'REJECT_KYC_FAIL';

export const SEARCH_LOGS_REQUEST = 'SEARCH_LOGS_REQUEST';
export const SEARCH_LOGS_SUCCESS = 'SEARCH_LOGS_SUCCESS';
export const SEARCH_LOGS_FAIL = 'SEARCH_LOGS_FAIL';

export const SELLER_LOCATION_UPDATE_REQUEST = 'SELLER_LOCATION_UPDATE_REQUEST';
export const SELLER_LOCATION_UPDATE_SUCCESS = 'SELLER_LOCATION_UPDATE_SUCCESS';
export const SELLER_LOCATION_UPDATE_FAIL = 'SELLER_LOCATION_UPDATE_FAIL';

export const ADMIN_DASHBOARD_STATS_REQUEST = 'ADMIN_DASHBOARD_STATS_REQUEST';
export const ADMIN_DASHBOARD_STATS_SUCCESS = 'ADMIN_DASHBOARD_STATS_SUCCESS';
export const ADMIN_DASHBOARD_STATS_FAIL = 'ADMIN_DASHBOARD_STATS_FAIL';

export const ADMIN_COMMENTS_MODERATION_REQUEST = 'ADMIN_COMMENTS_MODERATION_REQUEST';
export const ADMIN_COMMENTS_MODERATION_SUCCESS = 'ADMIN_COMMENTS_MODERATION_SUCCESS';
export const ADMIN_COMMENTS_MODERATION_FAIL = 'ADMIN_COMMENTS_MODERATION_FAIL';

// Admin Activities Constants - FIXED: Added missing constants
export const ADMIN_ACTIVITIES_REQUEST = 'ADMIN_ACTIVITIES_REQUEST';
export const ADMIN_ACTIVITIES_SUCCESS = 'ADMIN_ACTIVITIES_SUCCESS';
export const ADMIN_ACTIVITIES_FAIL = 'ADMIN_ACTIVITIES_FAIL';

// Admin Platform Overview Constants
export const ADMIN_PLATFORM_OVERVIEW_REQUEST = 'ADMIN_PLATFORM_OVERVIEW_REQUEST';
export const ADMIN_PLATFORM_OVERVIEW_SUCCESS = 'ADMIN_PLATFORM_OVERVIEW_SUCCESS';
export const ADMIN_PLATFORM_OVERVIEW_FAIL = 'ADMIN_PLATFORM_OVERVIEW_FAIL';

// Admin Recipe Analytics Constants
export const ADMIN_RECIPE_ANALYTICS_REQUEST = 'ADMIN_RECIPE_ANALYTICS_REQUEST';
export const ADMIN_RECIPE_ANALYTICS_SUCCESS = 'ADMIN_RECIPE_ANALYTICS_SUCCESS';
export const ADMIN_RECIPE_ANALYTICS_FAIL = 'ADMIN_RECIPE_ANALYTICS_FAIL';

// Analytics Export Constants
export const ADMIN_EXPORT_ANALYTICS_REQUEST = 'ADMIN_EXPORT_ANALYTICS_REQUEST';
export const ADMIN_EXPORT_ANALYTICS_SUCCESS = 'ADMIN_EXPORT_ANALYTICS_SUCCESS';
export const ADMIN_EXPORT_ANALYTICS_FAIL = 'ADMIN_EXPORT_ANALYTICS_FAIL';

// Dashboard Refresh Constants
export const ADMIN_DASHBOARD_REFRESH_REQUEST = 'ADMIN_DASHBOARD_REFRESH_REQUEST';
export const ADMIN_DASHBOARD_REFRESH_SUCCESS = 'ADMIN_DASHBOARD_REFRESH_SUCCESS';
export const ADMIN_DASHBOARD_REFRESH_FAIL = 'ADMIN_DASHBOARD_REFRESH_FAIL';

export const ADMIN_ANALYTICS_REQUEST = 'ADMIN_ANALYTICS_REQUEST';
export const ADMIN_ANALYTICS_SUCCESS = 'ADMIN_ANALYTICS_SUCCESS';
export const ADMIN_ANALYTICS_FAIL = 'ADMIN_ANALYTICS_FAIL';