export const DELIVERY_PARTNER_LIST_REQUEST = 'DELIVERY_PARTNER_LIST_REQUEST';
export const DELIVERY_PARTNER_LIST_SUCCESS = 'DELIVERY_PARTNER_LIST_SUCCESS';
export const DELIVERY_PARTNER_LIST_FAIL = 'DELIVERY_PARTNER_LIST_FAIL';

export const DELIVERY_PARTNER_CREATE_REQUEST = 'DELIVERY_PARTNER_CREATE_REQUEST';
export const DELIVERY_PARTNER_CREATE_SUCCESS = 'DELIVERY_PARTNER_CREATE_SUCCESS';
export const DELIVERY_PARTNER_CREATE_FAIL = 'DELIVERY_PARTNER_CREATE_FAIL';

export const DELIVERY_PARTNER_UPDATE_REQUEST = 'DELIVERY_PARTNER_UPDATE_REQUEST';
export const DELIVERY_PARTNER_UPDATE_SUCCESS = 'DELIVERY_PARTNER_UPDATE_SUCCESS';
export const DELIVERY_PARTNER_UPDATE_FAIL = 'DELIVERY_PARTNER_UPDATE_FAIL';

export const DELIVERY_PARTNER_DELETE_REQUEST = 'DELIVERY_PARTNER_DELETE_REQUEST';
export const DELIVERY_PARTNER_DELETE_SUCCESS = 'DELIVERY_PARTNER_DELETE_SUCCESS';
export const DELIVERY_PARTNER_DELETE_FAIL = 'DELIVERY_PARTNER_DELETE_FAIL';

export const DELIVERY_ASSIGN_REQUEST = 'DELIVERY_ASSIGN_REQUEST';
export const DELIVERY_ASSIGN_SUCCESS = 'DELIVERY_ASSIGN_SUCCESS';
export const DELIVERY_ASSIGN_FAIL = 'DELIVERY_ASSIGN_FAIL';

export const ORDER_LIST_FOR_DELIVERY_REQUEST = 'ORDER_LIST_FOR_DELIVERY_REQUEST';
export const ORDER_LIST_FOR_DELIVERY_SUCCESS = 'ORDER_LIST_FOR_DELIVERY_SUCCESS';
export const ORDER_LIST_FOR_DELIVERY_FAIL = 'ORDER_LIST_FOR_DELIVERY_FAIL';