// Forum Post Constants
export const FORUM_POST_CREATE_REQUEST = 'FORUM_POST_CREATE_REQUEST';
export const FORUM_POST_CREATE_SUCCESS = 'FORUM_POST_CREATE_SUCCESS';
export const FORUM_POST_CREATE_FAIL = 'FORUM_POST_CREATE_FAIL';
export const FORUM_POST_CREATE_RESET = 'FORUM_POST_CREATE_RESET';

export const FORUM_POST_LIST_REQUEST = 'FORUM_POST_LIST_REQUEST';
export const FORUM_POST_LIST_SUCCESS = 'FORUM_POST_LIST_SUCCESS';
export const FORUM_POST_LIST_FAIL = 'FORUM_POST_LIST_FAIL';

export const FORUM_POST_DETAILS_REQUEST = 'FORUM_POST_DETAILS_REQUEST';
export const FORUM_POST_DETAILS_SUCCESS = 'FORUM_POST_DETAILS_SUCCESS';
export const FORUM_POST_DETAILS_FAIL = 'FORUM_POST_DETAILS_FAIL';
export const FORUM_POST_DETAILS_RESET = 'FORUM_POST_DETAILS_RESET';

export const FORUM_POST_UPDATE_REQUEST = 'FORUM_POST_UPDATE_REQUEST';
export const FORUM_POST_UPDATE_SUCCESS = 'FORUM_POST_UPDATE_SUCCESS';
export const FORUM_POST_UPDATE_FAIL = 'FORUM_POST_UPDATE_FAIL';
export const FORUM_POST_UPDATE_RESET = 'FORUM_POST_UPDATE_RESET';

export const FORUM_POST_DELETE_REQUEST = 'FORUM_POST_DELETE_REQUEST';
export const FORUM_POST_DELETE_SUCCESS = 'FORUM_POST_DELETE_SUCCESS';
export const FORUM_POST_DELETE_FAIL = 'FORUM_POST_DELETE_FAIL';

export const FORUM_POST_LIKE_REQUEST = 'FORUM_POST_LIKE_REQUEST';
export const FORUM_POST_LIKE_SUCCESS = 'FORUM_POST_LIKE_SUCCESS';
export const FORUM_POST_LIKE_FAIL = 'FORUM_POST_LIKE_FAIL';

export const FORUM_POST_REPLY_REQUEST = 'FORUM_POST_REPLY_REQUEST';
export const FORUM_POST_REPLY_SUCCESS = 'FORUM_POST_REPLY_SUCCESS';
export const FORUM_POST_REPLY_FAIL = 'FORUM_POST_REPLY_FAIL';

export const FORUM_POST_APPROVE_REQUEST = 'FORUM_POST_APPROVE_REQUEST';
export const FORUM_POST_APPROVE_SUCCESS = 'FORUM_POST_APPROVE_SUCCESS';
export const FORUM_POST_APPROVE_FAIL = 'FORUM_POST_APPROVE_FAIL';

export const FORUM_POST_REPORT_REQUEST = 'FORUM_POST_REPORT_REQUEST';
export const FORUM_POST_REPORT_SUCCESS = 'FORUM_POST_REPORT_SUCCESS';
export const FORUM_POST_REPORT_FAIL = 'FORUM_POST_REPORT_FAIL';

export const FORUM_POST_PIN_REQUEST = 'FORUM_POST_PIN_REQUEST';
export const FORUM_POST_PIN_SUCCESS = 'FORUM_POST_PIN_SUCCESS';
export const FORUM_POST_PIN_FAIL = 'FORUM_POST_PIN_FAIL';

// NEW: Forum Comment Moderation Constants
export const FORUM_COMMENT_MODERATE_REQUEST = 'FORUM_COMMENT_MODERATE_REQUEST';
export const FORUM_COMMENT_MODERATE_SUCCESS = 'FORUM_COMMENT_MODERATE_SUCCESS';
export const FORUM_COMMENT_MODERATE_FAIL = 'FORUM_COMMENT_MODERATE_FAIL';

export const FORUM_COMMENT_REPORT_REQUEST = 'FORUM_COMMENT_REPORT_REQUEST';
export const FORUM_COMMENT_REPORT_SUCCESS = 'FORUM_COMMENT_REPORT_SUCCESS';
export const FORUM_COMMENT_REPORT_FAIL = 'FORUM_COMMENT_REPORT_FAIL';

export const FORUM_FLAGGED_COMMENTS_REQUEST = 'FORUM_FLAGGED_COMMENTS_REQUEST';
export const FORUM_FLAGGED_COMMENTS_SUCCESS = 'FORUM_FLAGGED_COMMENTS_SUCCESS';
export const FORUM_FLAGGED_COMMENTS_FAIL = 'FORUM_FLAGGED_COMMENTS_FAIL';

export const FORUM_POST_LIST_LIVE_REQUEST = 'FORUM_POST_LIST_LIVE_REQUEST';
export const FORUM_POST_LIST_LIVE_SUCCESS = 'FORUM_POST_LIST_LIVE_SUCCESS';
export const FORUM_POST_LIST_LIVE_FAIL = 'FORUM_POST_LIST_LIVE_FAIL';
