export const SUBMIT_KYC_REQUEST = 'SUBMIT_KYC_REQUEST';
export const SUBMIT_KYC_SUCCESS = 'SUBMIT_KYC_SUCCESS';
export const SUBMIT_KYC_FAIL = 'SUBMIT_KYC_FAIL';

export const KYC_APPLICATIONS_REQUEST = 'KYC_APPLICATIONS_REQUEST';
export const KYC_APPLICATIONS_SUCCESS = 'KYC_APPLICATIONS_SUCCESS';
export const KYC_APPLICATIONS_FAIL = 'KYC_APPLICATIONS_FAIL';

export const KYC_REVIEW_REQUEST = 'KYC_REVIEW_REQUEST';
export const KYC_REVIEW_SUCCESS = 'KYC_REVIEW_SUCCESS';
export const KYC_REVIEW_FAIL = 'KYC_REVIEW_FAIL';

export const KYC_SUBMIT_REQUEST = 'KYC_SUBMIT_REQUEST';
export const KYC_SUBMIT_SUCCESS = 'KYC_SUBMIT_SUCCESS';
export const KYC_SUBMIT_FAIL = 'KYC_SUBMIT_FAIL';

export const KYC_STATUS_REQUEST = 'KYC_STATUS_REQUEST';
export const KYC_STATUS_SUCCESS = 'KYC_STATUS_SUCCESS';
export const KYC_STATUS_FAIL = 'KYC_STATUS_FAIL';

export const APPROVE_KYC_REQUEST = 'APPROVE_KYC_REQUEST';
export const APPROVE_KYC_SUCCESS = 'APPROVE_KYC_SUCCESS';
export const APPROVE_KYC_FAIL = 'APPROVE_KYC_FAIL';