export const MESSAGE_SEND_REQUEST = 'MESSAGE_SEND_REQUEST';
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';
export const MESSAGE_SEND_FAIL = 'MESSAGE_SEND_FAIL';

export const MESSAGE_HISTORY_REQUEST = 'MESSAGE_HISTORY_REQUEST';
export const MESSAGE_HISTORY_SUCCESS = 'MESSAGE_HISTORY_SUCCESS';
export const MESSAGE_HISTORY_FAIL = 'MESSAGE_HISTORY_FAIL';

export const MESSAGE_ADMIN_REQUEST = 'MESSAGE_ADMIN_REQUEST';
export const MESSAGE_ADMIN_SUCCESS = 'MESSAGE_ADMIN_SUCCESS';
export const MESSAGE_ADMIN_FAIL = 'MESSAGE_ADMIN_FAIL';

export const MESSAGE_FLAG_REQUEST = 'MESSAGE_FLAG_REQUEST';
export const MESSAGE_FLAG_SUCCESS = 'MESSAGE_FLAG_SUCCESS';
export const MESSAGE_FLAG_FAIL = 'MESSAGE_FLAG_FAIL';

export const MESSAGE_DELETE_REQUEST = 'MESSAGE_DELETE_REQUEST';
export const MESSAGE_DELETE_SUCCESS = 'MESSAGE_DELETE_SUCCESS';
export const MESSAGE_DELETE_FAIL = 'MESSAGE_DELETE_FAIL';

export const MESSAGE_BLOCK_USER_REQUEST = 'MESSAGE_BLOCK_USER_REQUEST';
export const MESSAGE_BLOCK_USER_SUCCESS = 'MESSAGE_BLOCK_USER_SUCCESS';
export const MESSAGE_BLOCK_USER_FAIL = 'MESSAGE_BLOCK_USER_FAIL';

// New constants
export const MESSAGE_GET_REQUEST = 'MESSAGE_GET_REQUEST';
export const MESSAGE_GET_SUCCESS = 'MESSAGE_GET_SUCCESS';
export const MESSAGE_GET_FAIL = 'MESSAGE_GET_FAIL';