export const MODERATION_PENDING_REQUEST = 'MODERATION_PENDING_REQUEST';
export const MODERATION_PENDING_SUCCESS = 'MODERATION_PENDING_SUCCESS';
export const MODERATION_PENDING_FAIL = 'MODERATION_PENDING_FAIL';

export const MODERATION_FLAGGED_REQUEST = 'MODERATION_FLAGGED_REQUEST';
export const MODERATION_FLAGGED_SUCCESS = 'MODERATION_FLAGGED_SUCCESS';
export const MODERATION_FLAGGED_FAIL = 'MODERATION_FLAGGED_FAIL';

export const MODERATION_APPROVE_REQUEST = 'MODERATION_APPROVE_REQUEST';
export const MODERATION_APPROVE_SUCCESS = 'MODERATION_APPROVE_SUCCESS';
export const MODERATION_APPROVE_FAIL = 'MODERATION_APPROVE_FAIL';

export const MODERATION_REJECT_REQUEST = 'MODERATION_REJECT_REQUEST';
export const MODERATION_REJECT_SUCCESS = 'MODERATION_REJECT_SUCCESS';
export const MODERATION_REJECT_FAIL = 'MODERATION_REJECT_FAIL';

export const MODERATION_DELETE_REQUEST = 'MODERATION_DELETE_REQUEST';
export const MODERATION_DELETE_SUCCESS = 'MODERATION_DELETE_SUCCESS';
export const MODERATION_DELETE_FAIL = 'MODERATION_DELETE_FAIL';

export const MODERATION_PIN_REQUEST = 'MODERATION_PIN_REQUEST';
export const MODERATION_PIN_SUCCESS = 'MODERATION_PIN_SUCCESS';
export const MODERATION_PIN_FAIL = 'MODERATION_PIN_FAIL';

export const MODERATION_STATS_REQUEST = 'MODERATION_STATS_REQUEST';
export const MODERATION_STATS_SUCCESS = 'MODERATION_STATS_SUCCESS';
export const MODERATION_STATS_FAIL = 'MODERATION_STATS_FAIL';