export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST';
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL';

export const NOTIFICATION_MARK_READ_REQUEST = 'NOTIFICATION_MARK_READ_REQUEST';
export const NOTIFICATION_MARK_READ_SUCCESS = 'NOTIFICATION_MARK_READ_SUCCESS';
export const NOTIFICATION_MARK_READ_FAIL = 'NOTIFICATION_MARK_READ_FAIL';

export const NOTIFICATION_MARK_ALL_READ_REQUEST = 'NOTIFICATION_MARK_ALL_READ_REQUEST';
export const NOTIFICATION_MARK_ALL_READ_SUCCESS = 'NOTIFICATION_MARK_ALL_READ_SUCCESS';
export const NOTIFICATION_MARK_ALL_READ_FAIL = 'NOTIFICATION_MARK_ALL_READ_FAIL';

export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST';
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS';
export const NOTIFICATION_DELETE_FAIL = 'NOTIFICATION_DELETE_FAIL';

export const NOTIFICATION_CLEAR_ALL_REQUEST = 'NOTIFICATION_CLEAR_ALL_REQUEST';
export const NOTIFICATION_CLEAR_ALL_SUCCESS = 'NOTIFICATION_CLEAR_ALL_SUCCESS';
export const NOTIFICATION_CLEAR_ALL_FAIL = 'NOTIFICATION_CLEAR_ALL_FAIL';

export const NOTIFICATION_STATS_REQUEST = 'NOTIFICATION_STATS_REQUEST';
export const NOTIFICATION_STATS_SUCCESS = 'NOTIFICATION_STATS_SUCCESS';
export const NOTIFICATION_STATS_FAIL = 'NOTIFICATION_STATS_FAIL';

export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE';
export const NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE';

export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';