// ==============================
// DELIVERY PARTNER CONSTANTS
// ==============================
export const LIST_DELIVERY_PARTNERS_REQUEST = 'LIST_DELIVERY_PARTNERS_REQUEST';
export const LIST_DELIVERY_PARTNERS_SUCCESS = 'LIST_DELIVERY_PARTNERS_SUCCESS';
export const LIST_DELIVERY_PARTNERS_FAIL = 'LIST_DELIVERY_PARTNERS_FAIL';

export const CREATE_DELIVERY_PARTNER_REQUEST = 'CREATE_DELIVERY_PARTNER_REQUEST';
export const CREATE_DELIVERY_PARTNER_SUCCESS = 'CREATE_DELIVERY_PARTNER_SUCCESS';
export const CREATE_DELIVERY_PARTNER_FAIL = 'CREATE_DELIVERY_PARTNER_FAIL';

export const UPDATE_DELIVERY_PARTNER_REQUEST = 'UPDATE_DELIVERY_PARTNER_REQUEST';
export const UPDATE_DELIVERY_PARTNER_SUCCESS = 'UPDATE_DELIVERY_PARTNER_SUCCESS';
export const UPDATE_DELIVERY_PARTNER_FAIL = 'UPDATE_DELIVERY_PARTNER_FAIL';

export const DELETE_DELIVERY_PARTNER_REQUEST = 'DELETE_DELIVERY_PARTNER_REQUEST';
export const DELETE_DELIVERY_PARTNER_SUCCESS = 'DELETE_DELIVERY_PARTNER_SUCCESS';
export const DELETE_DELIVERY_PARTNER_FAIL = 'DELETE_DELIVERY_PARTNER_FAIL';

// ==============================
// SELLER CONSTANTS
// ==============================
export const UPDATE_SELLER_PROFILE_REQUEST = 'UPDATE_SELLER_PROFILE_REQUEST';
export const UPDATE_SELLER_PROFILE_SUCCESS = 'UPDATE_SELLER_PROFILE_SUCCESS';
export const UPDATE_SELLER_PROFILE_FAIL = 'UPDATE_SELLER_PROFILE_FAIL';

export const LIST_SELLER_ORDERS_REQUEST = 'LIST_SELLER_ORDERS_REQUEST';
export const LIST_SELLER_ORDERS_SUCCESS = 'LIST_SELLER_ORDERS_SUCCESS';
export const LIST_SELLER_ORDERS_FAIL = 'LIST_SELLER_ORDERS_FAIL';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAIL = 'UPDATE_ORDER_STATUS_FAIL';

// ==============================
// USER CONSTANTS
// ==============================
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const USER_WISHLIST_REQUEST = 'USER_WISHLIST_REQUEST';
export const USER_WISHLIST_SUCCESS = 'USER_WISHLIST_SUCCESS';
export const USER_WISHLIST_FAIL = 'USER_WISHLIST_FAIL';
export const USER_WISHLIST_ADD_ITEM = 'USER_WISHLIST_ADD_ITEM';
export const USER_WISHLIST_REMOVE_ITEM = 'USER_WISHLIST_REMOVE_ITEM';

// ==============================

// Order List All
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

// Order Details
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

// Create Order
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'; // <-- ADDED THIS LINE

// Pay for Order
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';

// My Orders
export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';

// Cancel Order
export const ORDER_CANCEL_REQUEST = 'ORDER_CANCEL_REQUEST';
export const ORDER_CANCEL_SUCCESS = 'ORDER_CANCEL_SUCCESS';
export const ORDER_CANCEL_FAIL = 'ORDER_CANCEL_FAIL';

// Deliver Order
export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL';

// Seller Order List
export const ORDER_LIST_SELLER_REQUEST = 'ORDER_LIST_SELLER_REQUEST';
export const ORDER_LIST_SELLER_SUCCESS = 'ORDER_LIST_SELLER_SUCCESS';
export const ORDER_LIST_SELLER_FAIL = 'ORDER_LIST_SELLER_FAIL';

// Order Update
export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';

// Delivery Partners
export const ORDER_DELIVERY_PARTNERS_REQUEST = 'ORDER_DELIVERY_PARTNERS_REQUEST';
export const ORDER_DELIVERY_PARTNERS_SUCCESS = 'ORDER_DELIVERY_PARTNERS_SUCCESS';
export const ORDER_DELIVERY_PARTNERS_FAIL = 'ORDER_DELIVERY_PARTNERS_FAIL';

// COD Report
export const ORDER_REPORT_COD_REQUEST = 'ORDER_REPORT_COD_REQUEST';
export const ORDER_REPORT_COD_SUCCESS = 'ORDER_REPORT_COD_SUCCESS';
export const ORDER_REPORT_COD_FAIL = 'ORDER_REPORT_COD_FAIL';


export const ASSIGN_DELIVERY_PARTNER_REQUEST = 'ASSIGN_DELIVERY_PARTNER_REQUEST';
export const ASSIGN_DELIVERY_PARTNER_SUCCESS = 'ASSIGN_DELIVERY_PARTNER_SUCCESS';
export const ASSIGN_DELIVERY_PARTNER_FAIL = 'ASSIGN_DELIVERY_PARTNER_FAIL';

export const UPLOAD_COD_PROOF_REQUEST = 'UPLOAD_COD_PROOF_REQUEST';
export const UPLOAD_COD_PROOF_SUCCESS = 'UPLOAD_COD_PROOF_SUCCESS';
export const UPLOAD_COD_PROOF_FAIL = 'UPLOAD_COD_PROOF_FAIL';