// frontend/src/redux/constants/paymentConstants.js

// Razorpay Order Creation (Frontend requests Order ID from backend)
export const RAZORPAY_ORDER_CREATE_REQUEST = 'RAZORPAY_ORDER_CREATE_REQUEST';
export const RAZORPAY_ORDER_CREATE_SUCCESS = 'RAZORPAY_ORDER_CREATE_SUCCESS';
export const RAZORPAY_ORDER_CREATE_FAIL = 'RAZORPAY_ORDER_CREATE_FAIL';
export const RAZORPAY_ORDER_CREATE_RESET = 'RAZORPAY_ORDER_CREATE_RESET'; // Added Reset

// Razorpay Payment Verification (Frontend sends payment details to backend)
export const RAZORPAY_VERIFY_REQUEST = 'RAZORPAY_VERIFY_REQUEST';
export const RAZORPAY_VERIFY_SUCCESS = 'RAZORPAY_VERIFY_SUCCESS';
export const RAZORPAY_VERIFY_FAIL = 'RAZORPAY_VERIFY_FAIL';
export const RAZORPAY_VERIFY_RESET = 'RAZORPAY_VERIFY_RESET'; // Added Reset

// Fetch Seller Payments Summary & History
export const SELLER_PAYMENTS_REQUEST = 'SELLER_PAYMENTS_REQUEST';
export const SELLER_PAYMENTS_SUCCESS = 'SELLER_PAYMENTS_SUCCESS';
export const SELLER_PAYMENTS_FAIL = 'SELLER_PAYMENTS_FAIL';

// Seller Records COD Payment Received
export const PAYMENT_RECORD_COD_REQUEST = 'PAYMENT_RECORD_COD_REQUEST';
export const PAYMENT_RECORD_COD_SUCCESS = 'PAYMENT_RECORD_COD_SUCCESS';
export const PAYMENT_RECORD_COD_FAIL = 'PAYMENT_RECORD_COD_FAIL';
export const PAYMENT_RECORD_COD_RESET = 'PAYMENT_RECORD_COD_RESET'; // Added Reset

// Seller Requests Payout
export const PAYOUT_REQUEST_REQUEST = 'PAYOUT_REQUEST_REQUEST';
export const PAYOUT_REQUEST_SUCCESS = 'PAYOUT_REQUEST_SUCCESS';
export const PAYOUT_REQUEST_FAIL = 'PAYOUT_REQUEST_FAIL';
export const PAYOUT_REQUEST_RESET = 'PAYOUT_REQUEST_RESET'; // Added Reset

// Fetch Seller Payout History (Maybe combine with SELLER_PAYMENTS or keep separate)
export const SELLER_PAYOUTS_HISTORY_REQUEST = 'SELLER_PAYOUTS_HISTORY_REQUEST';
export const SELLER_PAYOUTS_HISTORY_SUCCESS = 'SELLER_PAYOUTS_HISTORY_SUCCESS';
export const SELLER_PAYOUTS_HISTORY_FAIL = 'SELLER_PAYOUTS_HISTORY_FAIL';

// Admin Actions (Examples - Define if needed)
export const ADMIN_GET_PENDING_PAYOUTS_REQUEST = 'ADMIN_GET_PENDING_PAYOUTS_REQUEST';
export const ADMIN_GET_PENDING_PAYOUTS_SUCCESS = 'ADMIN_GET_PENDING_PAYOUTS_SUCCESS';
export const ADMIN_GET_PENDING_PAYOUTS_FAIL = 'ADMIN_GET_PENDING_PAYOUTS_FAIL';

export const ADMIN_PROCESS_PAYOUT_REQUEST = 'ADMIN_PROCESS_PAYOUT_REQUEST';
export const ADMIN_PROCESS_PAYOUT_SUCCESS = 'ADMIN_PROCESS_PAYOUT_SUCCESS';
export const ADMIN_PROCESS_PAYOUT_FAIL = 'ADMIN_PROCESS_PAYOUT_FAIL';

export const ADMIN_REFUND_REQUEST = 'ADMIN_REFUND_REQUEST';
export const ADMIN_REFUND_SUCCESS = 'ADMIN_REFUND_SUCCESS';
export const ADMIN_REFUND_FAIL = 'ADMIN_REFUND_FAIL';


export const PAYMENT_RECORD_REQUEST = 'PAYMENT_RECORD_REQUEST';
export const PAYMENT_RECORD_SUCCESS = 'PAYMENT_RECORD_SUCCESS';
export const PAYMENT_RECORD_FAIL = 'PAYMENT_RECORD_FAIL';