export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_FILTER_REQUEST = 'PRODUCT_FILTER_REQUEST';
export const PRODUCT_FILTER_SUCCESS = 'PRODUCT_FILTER_SUCCESS';
export const PRODUCT_FILTER_FAIL = 'PRODUCT_FILTER_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';

export const PRODUCT_SELLER_LIST_REQUEST = 'PRODUCT_SELLER_LIST_REQUEST';
export const PRODUCT_SELLER_LIST_SUCCESS = 'PRODUCT_SELLER_LIST_SUCCESS';
export const PRODUCT_SELLER_LIST_FAIL = 'PRODUCT_SELLER_LIST_FAIL';

export const PRODUCT_BULK_UPLOAD_REQUEST = 'PRODUCT_BULK_UPLOAD_REQUEST';
export const PRODUCT_BULK_UPLOAD_SUCCESS = 'PRODUCT_BULK_UPLOAD_SUCCESS';
export const PRODUCT_BULK_UPLOAD_FAIL = 'PRODUCT_BULK_UPLOAD_FAIL';

export const PRODUCT_ANALYTICS_REQUEST = 'PRODUCT_ANALYTICS_REQUEST';
export const PRODUCT_ANALYTICS_SUCCESS = 'PRODUCT_ANALYTICS_SUCCESS';
export const PRODUCT_ANALYTICS_FAIL = 'PRODUCT_ANALYTICS_FAIL';

export const RECIPE_SUGGESTION_REQUEST = 'RECIPE_SUGGESTION_REQUEST';
export const RECIPE_SUGGESTION_SUCCESS = 'RECIPE_SUGGESTION_SUCCESS';
export const RECIPE_SUGGESTION_FAIL = 'RECIPE_SUGGESTION_FAIL';

export const FORUM_POST_REQUEST = 'FORUM_POST_REQUEST';
export const FORUM_POST_SUCCESS = 'FORUM_POST_SUCCESS';
export const FORUM_POST_FAIL = 'FORUM_POST_FAIL';

export const SELLER_ANALYTICS_REQUEST = 'SELLER_ANALYTICS_REQUEST';
export const SELLER_ANALYTICS_SUCCESS = 'SELLER_ANALYTICS_SUCCESS';
export const SELLER_ANALYTICS_FAIL = 'SELLER_ANALYTICS_FAIL';

export const FORUM_MESSAGES_REQUEST = 'FORUM_MESSAGES_REQUEST';
export const FORUM_MESSAGES_SUCCESS = 'FORUM_MESSAGES_SUCCESS';
export const FORUM_MESSAGES_FAIL = 'FORUM_MESSAGES_FAIL';

export const SUGGEST_RECIPE_REQUEST = 'SUGGEST_RECIPE_REQUEST';
export const SUGGEST_RECIPE_SUCCESS = 'SUGGEST_RECIPE_SUCCESS';
export const SUGGEST_RECIPE_FAIL = 'SUGGEST_RECIPE_FAIL';

export const PRODUCT_APPROVE_REQUEST = 'PRODUCT_APPROVE_REQUEST';
export const PRODUCT_APPROVE_SUCCESS = 'PRODUCT_APPROVE_SUCCESS';
export const PRODUCT_APPROVE_FAIL = 'PRODUCT_APPROVE_FAIL';
export const PRODUCT_APPROVE_RESET = 'PRODUCT_APPROVE_RESET';

export const PRODUCT_LIST_PENDING_REQUEST = 'PRODUCT_LIST_PENDING_REQUEST';
export const PRODUCT_LIST_PENDING_SUCCESS = 'PRODUCT_LIST_PENDING_SUCCESS';
export const PRODUCT_LIST_PENDING_FAIL = 'PRODUCT_LIST_PENDING_FAIL';