// Recipe Constants
export const RECIPE_SUBMIT_REQUEST = 'RECIPE_SUBMIT_REQUEST';
export const RECIPE_SUBMIT_SUCCESS = 'RECIPE_SUBMIT_SUCCESS';
export const RECIPE_SUBMIT_FAIL = 'RECIPE_SUBMIT_FAIL';
export const RECIPE_SUBMIT_RESET = 'RECIPE_SUBMIT_RESET';

export const RECIPE_LIST_REQUEST = 'RECIPE_LIST_REQUEST';
export const RECIPE_LIST_SUCCESS = 'RECIPE_LIST_SUCCESS';
export const RECIPE_LIST_FAIL = 'RECIPE_LIST_FAIL';

export const RECIPE_LIST_MY_REQUEST = 'RECIPE_LIST_MY_REQUEST';
export const RECIPE_LIST_MY_SUCCESS = 'RECIPE_LIST_MY_SUCCESS';
export const RECIPE_LIST_MY_FAIL = 'RECIPE_LIST_MY_FAIL';

export const RECIPE_LIST_PENDING_REQUEST = 'RECIPE_LIST_PENDING_REQUEST';
export const RECIPE_LIST_PENDING_SUCCESS = 'RECIPE_LIST_PENDING_SUCCESS';
export const RECIPE_LIST_PENDING_FAIL = 'RECIPE_LIST_PENDING_FAIL';

export const RECIPE_DETAILS_REQUEST = 'RECIPE_DETAILS_REQUEST';
export const RECIPE_DETAILS_SUCCESS = 'RECIPE_DETAILS_SUCCESS';
export const RECIPE_DETAILS_FAIL = 'RECIPE_DETAILS_FAIL';
export const RECIPE_DETAILS_RESET = 'RECIPE_DETAILS_RESET';

export const RECIPE_APPROVE_REQUEST = 'RECIPE_APPROVE_REQUEST';
export const RECIPE_APPROVE_SUCCESS = 'RECIPE_APPROVE_SUCCESS';
export const RECIPE_APPROVE_FAIL = 'RECIPE_APPROVE_FAIL';
export const RECIPE_APPROVE_RESET = 'RECIPE_APPROVE_RESET';

export const RECIPE_RATE_REQUEST = 'RECIPE_RATE_REQUEST';
export const RECIPE_RATE_SUCCESS = 'RECIPE_RATE_SUCCESS';
export const RECIPE_RATE_FAIL = 'RECIPE_RATE_FAIL';
export const RECIPE_RATE_RESET = 'RECIPE_RATE_RESET';

export const RECIPE_COMMENT_REQUEST = 'RECIPE_COMMENT_REQUEST';
export const RECIPE_COMMENT_SUCCESS = 'RECIPE_COMMENT_SUCCESS';
export const RECIPE_COMMENT_FAIL = 'RECIPE_COMMENT_FAIL';
export const RECIPE_COMMENT_RESET = 'RECIPE_COMMENT_RESET';

export const RECIPE_DELETE_REQUEST = 'RECIPE_DELETE_REQUEST';
export const RECIPE_DELETE_SUCCESS = 'RECIPE_DELETE_SUCCESS';
export const RECIPE_DELETE_FAIL = 'RECIPE_DELETE_FAIL';

// NEW: Recipe Comment Moderation Constants
export const RECIPE_COMMENT_MODERATE_REQUEST = 'RECIPE_COMMENT_MODERATE_REQUEST';
export const RECIPE_COMMENT_MODERATE_SUCCESS = 'RECIPE_COMMENT_MODERATE_SUCCESS';
export const RECIPE_COMMENT_MODERATE_FAIL = 'RECIPE_COMMENT_MODERATE_FAIL';

export const RECIPE_COMMENT_REPORT_REQUEST = 'RECIPE_COMMENT_REPORT_REQUEST';
export const RECIPE_COMMENT_REPORT_SUCCESS = 'RECIPE_COMMENT_REPORT_SUCCESS';
export const RECIPE_COMMENT_REPORT_FAIL = 'RECIPE_COMMENT_REPORT_FAIL';

export const RECIPE_FLAGGED_COMMENTS_REQUEST = 'RECIPE_FLAGGED_COMMENTS_REQUEST';
export const RECIPE_FLAGGED_COMMENTS_SUCCESS = 'RECIPE_FLAGGED_COMMENTS_SUCCESS';
export const RECIPE_FLAGGED_COMMENTS_FAIL = 'RECIPE_FLAGGED_COMMENTS_FAIL';