export const REWARDS_REQUEST = 'REWARDS_REQUEST';
export const REWARDS_SUCCESS = 'REWARDS_SUCCESS';
export const REWARDS_FAIL = 'REWARDS_FAIL';

export const REWARD_TRANSACTIONS_REQUEST = 'REWARD_TRANSACTIONS_REQUEST';
export const REWARD_TRANSACTIONS_SUCCESS = 'REWARD_TRANSACTIONS_SUCCESS';
export const REWARD_TRANSACTIONS_FAIL = 'REWARD_TRANSACTIONS_FAIL';

export const REDEEM_REWARD_REQUEST = 'REDEEM_REWARD_REQUEST';
export const REDEEM_REWARD_SUCCESS = 'REDEEM_REWARD_SUCCESS';
export const REDEEM_REWARD_FAIL = 'REDEEM_REWARD_FAIL';
export const REDEEM_REWARD_RESET = 'REDEEM_REWARD_RESET';

export const CAMPAIGNS_REQUEST = 'CAMPAIGNS_REQUEST';
export const CAMPAIGNS_SUCCESS = 'CAMPAIGNS_SUCCESS';
export const CAMPAIGNS_FAIL = 'CAMPAIGNS_FAIL';

export const REFERRAL_CODE_REQUEST = 'REFERRAL_CODE_REQUEST';
export const REFERRAL_CODE_SUCCESS = 'REFERRAL_CODE_SUCCESS';
export const REFERRAL_CODE_FAIL = 'REFERRAL_CODE_FAIL';

export const REFERRALS_REQUEST = 'REFERRALS_REQUEST';
export const REFERRALS_SUCCESS = 'REFERRALS_SUCCESS';
export const REFERRALS_FAIL = 'REFERRALS_FAIL';

export const WALLET_DATA_REQUEST = 'WALLET_DATA_REQUEST';
export const WALLET_DATA_SUCCESS = 'WALLET_DATA_SUCCESS';
export const WALLET_DATA_FAIL = 'WALLET_DATA_FAIL';

export const WITHDRAW_REQUEST = 'WITHDRAW_REQUEST';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_FAIL = 'WITHDRAW_FAIL';
export const WITHDRAW_RESET = 'WITHDRAW_RESET';

export const WITHDRAWAL_HISTORY_REQUEST = 'WITHDRAWAL_HISTORY_REQUEST';
export const WITHDRAWAL_HISTORY_SUCCESS = 'WITHDRAWAL_HISTORY_SUCCESS';
export const WITHDRAWAL_HISTORY_FAIL = 'WITHDRAWAL_HISTORY_FAIL';

export const ADMIN_WITHDRAWAL_LIST_REQUEST = 'ADMIN_WITHDRAWAL_LIST_REQUEST';
export const ADMIN_WITHDRAWAL_LIST_SUCCESS = 'ADMIN_WITHDRAWAL_LIST_SUCCESS';
export const ADMIN_WITHDRAWAL_LIST_FAIL = 'ADMIN_WITHDRAWAL_LIST_FAIL';

export const ADMIN_WITHDRAWAL_UPDATE_REQUEST = 'ADMIN_WITHDRAWAL_UPDATE_REQUEST';
export const ADMIN_WITHDRAWAL_UPDATE_SUCCESS = 'ADMIN_WITHDRAWAL_UPDATE_SUCCESS';
export const ADMIN_WITHDRAWAL_UPDATE_FAIL = 'ADMIN_WITHDRAWAL_UPDATE_FAIL';
export const ADMIN_WITHDRAWAL_UPDATE_RESET = 'ADMIN_WITHDRAWAL_UPDATE_RESET';
