export const SOCIAL_LIKE_REQUEST = 'SOCIAL_LIKE_REQUEST'
export const SOCIAL_LIKE_SUCCESS = 'SOCIAL_LIKE_SUCCESS'
export const SOCIAL_LIKE_FAIL = 'SOCIAL_LIKE_FAIL'
export const SOCIAL_LIKE_RESET = 'SOCIAL_LIKE_RESET'

export const SOCIAL_COMMENT_REQUEST = 'SOCIAL_COMMENT_REQUEST'
export const SOCIAL_COMMENT_SUCCESS = 'SOCIAL_COMMENT_SUCCESS'
export const SOCIAL_COMMENT_FAIL = 'SOCIAL_COMMENT_FAIL'
export const SOCIAL_COMMENT_RESET = 'SOCIAL_COMMENT_RESET'

export const SOCIAL_GET_COMMENTS_REQUEST = 'SOCIAL_GET_COMMENTS_REQUEST'
export const SOCIAL_GET_COMMENTS_SUCCESS = 'SOCIAL_GET_COMMENTS_SUCCESS'
export const SOCIAL_GET_COMMENTS_FAIL = 'SOCIAL_GET_COMMENTS_FAIL'

export const SOCIAL_APPROVE_COMMENT_REQUEST = 'SOCIAL_APPROVE_COMMENT_REQUEST'
export const SOCIAL_APPROVE_COMMENT_SUCCESS = 'SOCIAL_APPROVE_COMMENT_SUCCESS'
export const SOCIAL_APPROVE_COMMENT_FAIL = 'SOCIAL_APPROVE_COMMENT_FAIL'

export const SOCIAL_DELETE_COMMENT_REQUEST = 'SOCIAL_DELETE_COMMENT_REQUEST'
export const SOCIAL_DELETE_COMMENT_SUCCESS = 'SOCIAL_DELETE_COMMENT_SUCCESS'
export const SOCIAL_DELETE_COMMENT_FAIL = 'SOCIAL_DELETE_COMMENT_FAIL'

export const SOCIAL_SHARE_REQUEST = 'SOCIAL_SHARE_REQUEST'
export const SOCIAL_SHARE_SUCCESS = 'SOCIAL_SHARE_SUCCESS'
export const SOCIAL_SHARE_FAIL = 'SOCIAL_SHARE_FAIL'

export const SOCIAL_COMMENT_LIKE_REQUEST = 'SOCIAL_COMMENT_LIKE_REQUEST'
export const SOCIAL_COMMENT_LIKE_SUCCESS = 'SOCIAL_COMMENT_LIKE_SUCCESS'
export const SOCIAL_COMMENT_LIKE_FAIL = 'SOCIAL_COMMENT_LIKE_FAIL'

export const SOCIAL_COMMENT_REPLY_REQUEST = 'SOCIAL_COMMENT_REPLY_REQUEST'
export const SOCIAL_COMMENT_REPLY_SUCCESS = 'SOCIAL_COMMENT_REPLY_SUCCESS'
export const SOCIAL_COMMENT_REPLY_FAIL = 'SOCIAL_COMMENT_REPLY_FAIL'

export const SOCIAL_RATING_DIST_REQUEST = 'SOCIAL_RATING_DIST_REQUEST'
export const SOCIAL_RATING_DIST_SUCCESS = 'SOCIAL_RATING_DIST_SUCCESS'
export const SOCIAL_RATING_DIST_FAIL = 'SOCIAL_RATING_DIST_FAIL'

// Social Types
export const SOCIAL_TYPE_PRODUCT = 'product'
export const SOCIAL_TYPE_RECIPE = 'recipe'
export const SOCIAL_TYPE_FORUM = 'forum'