export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';
export const USER_CHANGE_PASSWORD_REQUEST = 'USER_CHANGE_PASSWORD_REQUEST';
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_FAIL = 'USER_CHANGE_PASSWORD_FAIL';
export const USER_CHANGE_PASSWORD_RESET = 'USER_CHANGE_PASSWORD_RESET';
export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_FAIL = 'USER_FORGOT_PASSWORD_FAIL';
export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_FAIL = 'USER_RESET_PASSWORD_FAIL';
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';
export const USER_WISHLIST_REQUEST = 'USER_WISHLIST_REQUEST';
export const USER_WISHLIST_SUCCESS = 'USER_WISHLIST_SUCCESS';
export const USER_WISHLIST_FAIL = 'USER_WISHLIST_FAIL';
export const USER_WISHLIST_ADD_ITEM = 'USER_WISHLIST_ADD_ITEM';
export const USER_WISHLIST_REMOVE_ITEM = 'USER_WISHLIST_REMOVE_ITEM';
export const LIST_DELIVERY_PARTNERS_REQUEST = 'LIST_DELIVERY_PARTNERS_REQUEST';
export const LIST_DELIVERY_PARTNERS_SUCCESS = 'LIST_DELIVERY_PARTNERS_SUCCESS';
export const LIST_DELIVERY_PARTNERS_FAIL = 'LIST_DELIVERY_PARTNERS_FAIL';
export const CREATE_DELIVERY_PARTNER_REQUEST = 'CREATE_DELIVERY_PARTNER_REQUEST';
export const CREATE_DELIVERY_PARTNER_SUCCESS = 'CREATE_DELIVERY_PARTNER_SUCCESS';
export const CREATE_DELIVERY_PARTNER_FAIL = 'CREATE_DELIVERY_PARTNER_FAIL';
export const UPDATE_DELIVERY_PARTNER_REQUEST = 'UPDATE_DELIVERY_PARTNER_REQUEST';
export const UPDATE_DELIVERY_PARTNER_SUCCESS = 'UPDATE_DELIVERY_PARTNER_SUCCESS';
export const UPDATE_DELIVERY_PARTNER_FAIL = 'UPDATE_DELIVERY_PARTNER_FAIL';
export const DELETE_DELIVERY_PARTNER_REQUEST = 'DELETE_DELIVERY_PARTNER_REQUEST';
export const DELETE_DELIVERY_PARTNER_SUCCESS = 'DELETE_DELIVERY_PARTNER_SUCCESS';
export const DELETE_DELIVERY_PARTNER_FAIL = 'DELETE_DELIVERY_PARTNER_FAIL';
export const SELLER_UPDATE_PROFILE_REQUEST = 'SELLER_UPDATE_PROFILE_REQUEST';
export const SELLER_UPDATE_PROFILE_SUCCESS = 'SELLER_UPDATE_PROFILE_SUCCESS';
export const SELLER_UPDATE_PROFILE_FAIL = 'SELLER_UPDATE_PROFILE_FAIL';
export const USER_DELETE_ACCOUNT_REQUEST = 'USER_DELETE_ACCOUNT_REQUEST';
export const USER_DELETE_ACCOUNT_SUCCESS = 'USER_DELETE_ACCOUNT_SUCCESS';
export const USER_DELETE_ACCOUNT_FAIL = 'USER_DELETE_ACCOUNT_FAIL';
export const USER_RESET_PREFERENCES_REQUEST = 'USER_RESET_PREFERENCES_REQUEST';
export const USER_RESET_PREFERENCES_SUCCESS = 'USER_RESET_PREFERENCES_SUCCESS';
export const USER_RESET_PREFERENCES_FAIL = 'USER_RESET_PREFERENCES_FAIL';
export const USER_RESET_PREFERENCES_RESET = 'USER_RESET_PREFERENCES_RESET';

export const USER_LINK_ACCOUNT_REQUEST = 'USER_LINK_ACCOUNT_REQUEST';
export const USER_LINK_ACCOUNT_SUCCESS = 'USER_LINK_ACCOUNT_SUCCESS';
export const USER_LINK_ACCOUNT_FAIL = 'USER_LINK_ACCOUNT_FAIL';

export const USER_UNLINK_ACCOUNT_REQUEST = 'USER_UNLINK_ACCOUNT_REQUEST';
export const USER_UNLINK_ACCOUNT_SUCCESS = 'USER_UNLINK_ACCOUNT_SUCCESS';
export const USER_UNLINK_ACCOUNT_FAIL = 'USER_UNLINK_ACCOUNT_FAIL';

export const USER_ADD_PAYMENT_REQUEST = 'USER_ADD_PAYMENT_REQUEST';
export const USER_ADD_PAYMENT_SUCCESS = 'USER_ADD_PAYMENT_SUCCESS';
export const USER_ADD_PAYMENT_FAIL = 'USER_ADD_PAYMENT_FAIL';

export const USER_DELETE_PAYMENT_REQUEST = 'USER_DELETE_PAYMENT_REQUEST';
export const USER_DELETE_PAYMENT_SUCCESS = 'USER_DELETE_PAYMENT_SUCCESS';
export const USER_DELETE_PAYMENT_FAIL = 'USER_DELETE_PAYMENT_FAIL';

export const USER_GET_REWARDS_REQUEST = 'USER_GET_REWARDS_REQUEST';
export const USER_GET_REWARDS_SUCCESS = 'USER_GET_REWARDS_SUCCESS';
export const USER_GET_REWARDS_FAIL = 'USER_GET_REWARDS_FAIL';

export const USER_SUBSCRIBE_REQUEST = 'USER_SUBSCRIBE_REQUEST';
export const USER_SUBSCRIBE_SUCCESS = 'USER_SUBSCRIBE_SUCCESS';
export const USER_SUBSCRIBE_FAIL = 'USER_SUBSCRIBE_FAIL';

export const USER_UNSUBSCRIBE_REQUEST = 'USER_UNSUBSCRIBE_REQUEST';
export const USER_UNSUBSCRIBE_SUCCESS = 'USER_UNSUBSCRIBE_SUCCESS';
export const USER_UNSUBSCRIBE_FAIL = 'USER_UNSUBSCRIBE_FAIL';

export const USER_REPORT_PROBLEM_REQUEST = 'USER_REPORT_PROBLEM_REQUEST';
export const USER_REPORT_PROBLEM_SUCCESS = 'USER_REPORT_PROBLEM_SUCCESS';
export const USER_REPORT_PROBLEM_FAIL = 'USER_REPORT_PROBLEM_FAIL';

export const USER_EXPORT_DATA_REQUEST = 'USER_EXPORT_DATA_REQUEST';
export const USER_EXPORT_DATA_SUCCESS = 'USER_EXPORT_DATA_SUCCESS';
export const USER_EXPORT_DATA_FAIL = 'USER_EXPORT_DATA_FAIL';

export const USER_GET_SUBSCRIPTION_REQUEST = 'USER_GET_SUBSCRIPTION_REQUEST';
export const USER_GET_SUBSCRIPTION_SUCCESS = 'USER_GET_SUBSCRIPTION_SUCCESS';
export const USER_GET_SUBSCRIPTION_FAIL    = 'USER_GET_SUBSCRIPTION_FAIL';