export const REFUND_REQUEST_CREATE_REQUEST = 'REFUND_REQUEST_CREATE_REQUEST';
export const REFUND_REQUEST_CREATE_SUCCESS = 'REFUND_REQUEST_CREATE_SUCCESS';
export const REFUND_REQUEST_CREATE_FAIL = 'REFUND_REQUEST_CREATE_FAIL';
export const REFUND_REQUEST_CREATE_RESET = 'REFUND_REQUEST_CREATE_RESET';

export const REFUND_LIST_REQUEST = 'REFUND_LIST_REQUEST';
export const REFUND_LIST_SUCCESS = 'REFUND_LIST_SUCCESS';
export const REFUND_LIST_FAIL = 'REFUND_LIST_FAIL';

export const REFUND_DETAILS_REQUEST = 'REFUND_DETAILS_REQUEST';
export const REFUND_DETAILS_SUCCESS = 'REFUND_DETAILS_SUCCESS';
export const REFUND_DETAILS_FAIL = 'REFUND_DETAILS_FAIL';
