export const WALLET_DATA_REQUEST = 'WALLET_DATA_REQUEST';
export const WALLET_DATA_SUCCESS = 'WALLET_DATA_SUCCESS';
export const WALLET_DATA_FAIL = 'WALLET_DATA_FAIL';

export const WITHDRAW_REQUEST = 'WITHDRAW_REQUEST';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_FAIL = 'WITHDRAW_FAIL';
export const WITHDRAW_RESET = 'WITHDRAW_RESET';

export const WITHDRAWAL_HISTORY_REQUEST = 'WITHDRAWAL_HISTORY_REQUEST';
export const WITHDRAWAL_HISTORY_SUCCESS = 'WITHDRAWAL_HISTORY_SUCCESS';
export const WITHDRAWAL_HISTORY_FAIL = 'WITHDRAWAL_HISTORY_FAIL';
