export const BULK_ORDER_CREATE_REQUEST = 'BULK_ORDER_CREATE_REQUEST';
export const BULK_ORDER_CREATE_SUCCESS = 'BULK_ORDER_CREATE_SUCCESS';
export const BULK_ORDER_CREATE_FAIL = 'BULK_ORDER_CREATE_FAIL';

export const BULK_ORDER_LIST_REQUEST = 'BULK_ORDER_LIST_REQUEST';
export const BULK_ORDER_LIST_SUCCESS = 'BULK_ORDER_LIST_SUCCESS';
export const BULK_ORDER_LIST_FAIL = 'BULK_ORDER_LIST_FAIL';

export const BULK_ORDER_DETAILS_REQUEST = 'BULK_ORDER_DETAILS_REQUEST';
export const BULK_ORDER_DETAILS_SUCCESS = 'BULK_ORDER_DETAILS_SUCCESS';
export const BULK_ORDER_DETAILS_FAIL = 'BULK_ORDER_DETAILS_FAIL';

export const BULK_ORDER_UPDATE_REQUEST = 'BULK_ORDER_UPDATE_REQUEST';
export const BULK_ORDER_UPDATE_SUCCESS = 'BULK_ORDER_UPDATE_SUCCESS';
export const BULK_ORDER_UPDATE_FAIL = 'BULK_ORDER_UPDATE_FAIL';
