name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      JWT_SECRET: "test_jwt_secret_which_needs_to_be_long_enough_for_security"
      REFRESH_TOKEN_SECRET: "test_refresh_secret"
      MONGO_URI: "mongodb://127.0.0.1:27017/dummy" # Mocked out by mongodb-memory-server
      NODE_ENV: "test"

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
        
    - name: Install dependencies
      run: npm ci || npm install --legacy-peer-deps
      
    - name: Run tests
      run: npm test
